### ISSUE TITLE
todo, benchmark individual esnext-filters

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/basic-transpiler-benchmarks#3]
- [x]  [arrow functions][features-arrows](via [es6-arrow-function][es6-arrow-function])
- [x] [classes][features-classes](via [es6-class][es6-class])
- [x] [computed property keys][features-enhanced-object-literals](via [es6-computed-property-keys][es6-computed-property-keys])
- [x] [computed property keys][features-enhanced-object-literals](via [es6-computed-properties][es6-computed-properties])
- [x] [default params][features-default-rest-spread](via [es6-default-params][es6-default-params])
- [x] [destructuring][features-destructuring](via [es6-destructuring][es6-destructuring])
- [x] [generators][features-generators](via [regenerator][regenerator])
- [x] [async-await](https://github.com/lukehoban/ecmascript-asyncawait) (via [regenerator][regenerator])
- [x] [iterators + for-of][features-iterators-for-of](via [regenerator][regenerator])
- [x] [object literal concise definitions][features-enhanced-object-literals](via [es6-object-concise][es6-object-concise])
- [x] [object literal shorthand][features-enhanced-object-literals](via [es6-object-short][es6-object-short])
- [x] [rest params][features-default-rest-spread](via [es6-rest-params][es6-rest-params])
- [x] [spread][features-default-rest-spread](via [es6-spread][es6-spread])
- [x] [template strings][features-template-strings](via [es6-templates][es6-templates])
- [x] [unicode regexes][features-unicode](via [regexpu][regexpu])

---
- [ ] make it easy to compare runs
